/**
	Class contains constants.
*/
public with sharing class Utils {

	//Opportunity Stage Picklist values
	public static final String OPP_STAGE_CLOSED_LOST = 'Closed Lost';
	public static final String OPP_STAGE_CLOSED_WON = 'Closed Won';

	public static void FakeCoverageMethod() {
		Integer i=0;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
	}
}